### ISSUE TITLE
Train single model 

### ISSUE THREAD

**Issue by jainspoornima** [zaccharieramzi/fastmri-reproducible-benchmark#146] opened 2021-09-12 09:43 UTC
I wished to train only the UNet model on fastmri data. For this, I used the following code -
```
from fastmri_recon.models.subclassed_models import unet
model = unet.UnetComplex(n_input_channels=2)
```

I wish to ask how to preprocess the fastmri data to train this model on it.
Thanks.

**Comment by zaccharieramzi** [comment] 2021-09-13 15:04
Hi @jainspoornima ,

Thanks for taking an interest in this repo.
[Here](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/fastmri_recon/training_scripts/updnet_train.py), you can find an example of how to train a neural network (in this case the UPDNet) on the fastMRI dataset.

In order to train with the UNet you would simply have to replace the UPDNet by the UNet.
Don't forget to adapt the parameters, in particular, using the `dealiasing_nc_fastmri` to output a magnitude image.

If you want to customize the preprocessing of the data, I would suggest looking into the [example datasets](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/fastmri_recon/data/datasets/fastmri_pyfunc.py#L23), or even [this repo](https://github.com/zaccharieramzi/tf-fastmri-data).

**Comment by jainspoornima** [comment] 2021-09-15 10:52
Thanks dear Zaccharie Ramzi sir for your response.
As the PDNet performed the best in the paper "Benchmarking MRI
Reconstruction Neural Networks on Large Public Datasets", I was trying to
train it on a small subset of fastMRI dataset.

I used the following command for ''pdnet_approach.py'' file in
''fastmri_recon/training_scripts/single_coil/'' folder using the command -
!python -m pdnet_approach

My data is in the directory structure
singlecoil_data
                |_singlecoil_train
                                   |_singlecoil_train
                |_singlecoil_val
and  I have provided the path of the singlecoil_data folder in the
''fastmri_recon/config.py'' file.

Actually I have just used the 18 GB split of validation data of fastMRI
data and split it into the above train and validation folders due to
compute limitations.

But I am getting the following error  -
ValueError: Input 1 is incompatible with layer model: expected shape=(None,
640, None), found shape=(None, 1, None)

in the model.fit statement in the file.

Could you please help me with debugging it or share how I can debug it?

Thanks and regards,
Poornima

**Comment by zaccharieramzi** [comment] 2021-09-16 12:42
Hi @jainspoornima ,

I am able to reproduce this bug, I will try to tackle it.
Thanks for bringing this up.

If I may, for our next interactions (but also to use everywhere on GitHub), I suggest using the markdown syntax to highlight code, stacktraces or even tree structure. You can find more about this here: https://guides.github.com/features/mastering-markdown/#examples

**Comment by zaccharieramzi** [comment] 2021-09-16 13:11
You should now be able to use the script.

However I would like to point out several things: if you do not use the training and validation set provided by fastMRI, you will not be able to reproduce the results of the paper. Moreover, to train these networks, you do need a large amount of compute (like a recent GPU with 16Gb of RAM), so I think it's important to somehow get access to one. Also if you meant that you didn't have enough space on your disk to store the training data, I also suggest finding a way to store it because it's far from being the biggest to work on in MRI reconstruction.

I am closing this, but do not hesitate to keep the discussion going or open a new issue should another bug arise.

**Closed by zaccharieramzi** 2021-09-16 13:11 UTC
