### ISSUE TITLE
KeyError: 'metrics' in unet_approach training

### ISSUE THREAD

**Issue by fharman** [zaccharieramzi/fastmri-reproducible-benchmark#95] opened 2020-09-09 12:07 UTC
Hi everyone,

Now, i encountered a training error. It is

```
Training: 0%
0/10 [00:00<?, ?it/s]
Epoch 0: 0%
0/5 [00:00<?, ?it/s]

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-8-bf021aacb644> in <module>
----> 1 model.fit(
      2     train_set,
      3     steps_per_epoch=5,
      4     epochs=n_epochs,
      5     validation_data=val_set,

~/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

~/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    853                 context.async_wait()
    854               logs = tmp_logs  # No error, now safe to assign to logs.
--> 855               callbacks.on_train_batch_end(step, logs)
    856         epoch_logs = copy.copy(logs)
    857 

~/.local/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py in on_train_batch_end(self, batch, logs)
    388     if self._should_call_train_batch_hooks:
    389       logs = self._process_logs(logs)
--> 390       self._call_batch_hook(ModeKeys.TRAIN, 'end', batch, logs=logs)
    391 
    392   def on_test_batch_begin(self, batch, logs=None):

~/.local/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py in _call_batch_hook(self, mode, hook, batch, logs)
    296     for callback in self.callbacks:
    297       batch_hook = getattr(callback, hook_name)
--> 298       batch_hook(batch, logs)
    299     self._delta_ts[hook_name].append(time.time() - t_before_callbacks)
    300 

~/.local/lib/python3.8/site-packages/keras_tqdm/tqdm_callback.py in on_batch_end(self, batch, logs)
    115         self.inner_count += update
    116         if self.inner_count < self.inner_total:
--> 117             self.append_logs(logs)
    118             metrics = self.format_metrics(self.running_logs)
    119             desc = self.inner_description_update.format(epoch=self.epoch, metrics=metrics)

~/.local/lib/python3.8/site-packages/keras_tqdm/tqdm_callback.py in append_logs(self, logs)
    134 
    135     def append_logs(self, logs):
--> 136         metrics = self.params['metrics']
    137         for metric, value in six.iteritems(logs):
    138             if metric in metrics:

KeyError: 'metrics'
```

Have anyone faced a problem like this? How did you solve this problem?

Thank you for your help, Stay safe

Best regards,

**Comment by fharman** [comment] 2020-09-09 12:09
Thank you for editting!

**Comment by zaccharieramzi** [comment] 2020-09-09 14:25
I could reproduce the error. I will come up with a fix.

**Comment by zaccharieramzi** [comment] 2020-09-09 14:39
This should be solved in #96 , I will merge once all the tests pass (which they should because the old functional training scripts are not tested unfortunately).

**Comment by fharman** [comment] 2020-09-09 14:42
hi again,

it is still working in terminal (attached as a screenshot) but not working
jupyter notebook.

thank you!

Zaccharie Ramzi <notifications@github.com>, 9 Eyl 2020 Çar, 17:26 tarihinde
şunu yazdı:

**Comment by fharman** [comment] 2020-09-09 14:43
But there is still a metrics error as you see in the screenshot

fatma harman <fatmaharman89@gmail.com>, 9 Eyl 2020 Çar, 17:42 tarihinde
şunu yazdı:

**Comment by zaccharieramzi** [comment] 2020-09-09 15:02
Well for now I haven't merged anything, so it's normal that nothing has changed.

What do you expect to do in a jupyter notebook?
What you pointed out is a script, so typically you wouldn't use it in a jupyter notebook.

**Comment by fharman** [comment] 2020-09-09 15:07
hi again,

just  only seeing the result of  import tensorflow as tf
from tensorflow_addons import tfa. thats all.

in my terminal , it is still working in spite of metrics error. i am
waiting its finish from 3 hours.

thank you for all help,

best regards

Zaccharie Ramzi <notifications@github.com>, 9 Eyl 2020 Çar, 18:02 tarihinde
şunu yazdı:

**Comment by zaccharieramzi** [comment] 2020-09-09 15:08
I think it's best if you wait for the PR I mentioned earlier to be merged.
If things seem to be working then you should be fine, glad I could help.

**Comment by zaccharieramzi** [comment] 2020-09-10 08:29
This should now be fixed!

**Closed by zaccharieramzi** 2020-09-10 08:29 UTC

**Comment by fharman** [comment] 2020-09-10 09:06
Thank you very much, i have  been still waiting ex-unet_approach.py running
finish since yesterday. it is still working in spite of metrics errors.

have a nice day, stay safe;

best regards

Zaccharie Ramzi <notifications@github.com>, 10 Eyl 2020 Per, 11:29
tarihinde şunu yazdı:

**Comment by fharman** [comment] 2020-11-19 15:23
Sizinle bir öğe paylaştım:

Validation Metrics for Unet.ipynb
https://colab.research.google.com/drive/157wHYIrS2JMv6df0i_MF58DaThGhzKiT?invite=CLWx5ocJ&ts=5fb68e08

Bu öğe ek değildir, çevrimiçi olarak depolanmaktadır. Söz konusu öğeyi  
açmak için yukarıdaki bağlantıyı tıklamanız yeterlidir.

Hi everyone,

Thank you for all your support. Finally, i had a  new better result in  
comparison with zerofilled.

Thank you Zaccharie,

Best Regards,

**Comment by zaccharieramzi** [comment] 2020-11-19 15:34
Cool, glad I could help.
Sorry for this being confusing, I will try in the near future to clean this up, in order for everyone to be able to use this seamlessly.
