### ISSUE TITLE
Nufft and its adj operator with cropped 320x320 image

### ISSUE THREAD

**Issue by TequilaSR** [zaccharieramzi/fastmri-reproducible-benchmark#169] opened 2021-12-24 05:25 UTC
When I try to only apply Nufft and its adj operator with radial trajectory on my cropped 320x320 image from fastMRI without acceleration/undersampling I cannot get a clean result (comparing to its ground truth under Cartesian sampling there are some white artifects). But in your original code with im_size set to (640,400) for the original fastMRI kspace it seems fine. For my own experiment I cropped the image generated from the full kspace to (320,320) and changed the im_size parameter to (320,320) to generate the trajectory with the af/us set to None. I follow the process applying nufft and adjnufft as shown in `fastmri_recon/data/datasets/preprocessing.py`  and `fastmri_recon/models/subclassed_models/unet.py`  with data compensate mode turned on.  Is there anything wrong with my parameter setting? Please help me solve this problem and thank you very much!

**Comment by zaccharieramzi** [comment] 2021-12-24 09:29
Hello !

Could you show us a minimal reproducible example please in order for us to help as best as we can?
Ideally this would be in a colab where we can just run it to see what's happening.

Also I am wondering whether this should be in this repo or in tfkbnufft. Is there anything related to the reconstruction networks in your issue?

**Comment by TequilaSR** [comment] 2021-12-26 14:29
Thanks for the reply!
I just tried to check whether I can use tfkbnufft to simulate the non-Cartesian data from the reconstruction_esc of fastMRI dataset and it has nothing to do with the reconstruction network . Here's the code :
```
import h5py
import os
from matplotlib import pyplot as plt
from data.utils.non_cartesian import get_radial_trajectory
from models.utils.fourier import tf_unmasked_adj_op, nufft, FFTBase, AdjNFFT
import tensorflow as tf
from tfkbnufft import kbnufft_forward, kbnufft_adjoint
from tfkbnufft.mri.dcomp_calc import calculate_density_compensator
from tfkbnufft.kbnufft import KbNufftModule

path='./singlecoil_val/'
files = os.listdir(path)
image_size = (320, 320)
traj = get_radial_trajectory((320, 320), af=1)
for i, file in enumerate(files):
    with h5py.File(f'{path}{file}', 'r') as f:
        gt = f['reconstruction_esc'][15]
        gt = tf.convert_to_tensor(gt[None, :, :, None], dtype=tf.complex64)
        nufft_ob = KbNufftModule(
            im_size=image_size,
            grid_size=None,
            norm='ortho',
        )
        interpob = nufft_ob._extract_nufft_interpob()
        nufftob_back = kbnufft_adjoint(interpob, multiprocessing=True)
        nufftob_forw = kbnufft_forward(interpob, multiprocessing=True)
        dcomp = calculate_density_compensator(
        interpob,
        nufftob_forw,
        nufftob_back,
        traj[0],
        )
        nc_kspace = nufft(nufft_ob, gt[:, None, ..., 0], traj, image_size)
        nc_kspace_channeled = nc_kspace[..., None]
        orig_shape = tf.ones([tf.shape(nc_kspace_channeled)[0]], dtype=tf.int32) * image_size[-1]
        dcomp = tf.ones([1, tf.shape(dcomp)[0]], dtype=dcomp.dtype) * dcomp[None, :]
        adj_op = AdjNFFT(
            im_size=image_size,
            multicoil=False,
            density_compensation=True,
            grad_traj=False,
        )
        input=[nc_kspace_channeled,traj,orig_shape,dcomp]
        image=adj_op(input)
        plt.subplot(121)
        plt.axis('off')
        plt.title('input')
        plt.imshow(abs(gt[0, ...]), cmap='gray')
        plt.subplot(122)
        plt.axis('off')
        plt.title('adjnufft result')
        plt.imshow(abs(image[0,:,:,0]), cmap='gray')
        plt.show()
```
I want to know why there are artifacts in the result and how to fix it . Thank you !

**Comment by zaccharieramzi** [comment] 2021-12-26 19:19
I agree that this is weird. Let me look into it.

On a totally different topic: why do you want to retrospectively undersample magnitude data, rather than raw data (i.e. complex-valued)?

**Comment by zaccharieramzi** [comment] 2021-12-26 19:34
Actually I know why: when you use the acceleration factor of 1 for the radial trajectory, you are still under the Nyquist criterion because the acceleration factor is calculated compared to a fully sampled Cartesian acquisition.
Therefore, an acceleration factor of 1 means an undersampling factor > 1 for the radial trajectory.

Also, in the fastMRI dataset, there is an oversampling factor in the readout dimension of 2. You should use this when creating the radial trajectory, i.e. `traj = get_radial_trajectory((320, 640), af=1)` or `traj = get_radial_trajectory((320, 640), us=1)`.

**Comment by TequilaSR** [comment] 2021-12-27 04:59
Thanks a lot!
When I change it to `traj = get_radial_trajectory((640, 320), af=1)`  it turns to be fine.

> On a totally different topic: why do you want to retrospectively undersample magnitude data, rather than raw data (i.e. complex-valued)?

The reason for checking this is that I've noticed there are so many cropping and padding process in this repo for handling the data. I try to generate a dataset with fixed size of (320,320) in the hdf5 form to simplify the pipeline.
To get this maybe I should first transform the original kspace data to the complex valued image and cut it to (320,320) instead of using the magnitude data directly.

**Comment by zaccharieramzi** [comment] 2021-12-27 07:31
Yes I have indeed a bit of a complex machinery to deal with the different sizes... There might be a better way.

Regarding the trajectory, if you use `(640, 320)` instead of `(320, 640)`, you will have more shots than expected for the acceleration factor.

**Comment by TequilaSR** [comment] 2021-12-27 09:22
I changed it to `traj = get_radial_trajectory((320, 640), af=1)` but there're still artifacts in the results...

**Comment by zaccharieramzi** [comment] 2021-12-28 11:52
Yes you are right, my bad, it was indeed `(640, 320)` to have the oversampled spokelength.

Also re the magnitude data, I think it would be best indeed to use the complex-valued kspace to get the image and crop it.

Closing this since I think we do not have anything further to discuss but feel free to re-open if needed.

**Closed by zaccharieramzi** 2021-12-28 11:52 UTC
